# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57381bc11794b2412878cee425243957fa7095b1ef4afd62bac1de5bc0edabb9af86106e17c09ceecf900a62bf589733f8b0e256c64174a1b16656da4d5a36ec

test:
  secret_key_base: ad88c6982ef396db8ce941afd3049d878e8d54bf41bde20cc4affb20c7f310dde57bdff1e82af6516ad149e6ab60ac12a543fa2b7a2f780c6739541f01c09066

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
